const ADD_TO_CART = 'ADD_TO_CART';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
const UPDATE_QUANTITY = 'UPDATE_QUANTITY';
const EMPTY_CART = 'EMPTY_CART';
// const REMOVE_QUANTITY = 'REMOVE_QUANTITY';

export { ADD_TO_CART, REMOVE_FROM_CART, UPDATE_QUANTITY, EMPTY_CART }